name: algorithm_visualizer
description: A simple algorithm visualizer project application.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.1
  provider: ^5.0.0

dev_dependencies:
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1

flutter:
  uses-material-design: true
